# action.yml
name: PR linked issues
description: Get issues linked to pull request
author: mondeja
inputs:
  repository_owner:
    description: The owner of the repository where is located the pull request.
    required: false
  repository_name:
    description: The name of the repository where is located the pull request.
    required: false
  pull_request:
    description: Number of the pull request for which linked pull requests will be retrieved.
    required: false
  owners:
    description: Indicate that the action will output `opener` and `others`, showing in them the linked issues opened by the pull request owner (`opener`) and those opened by other users (`others`).
    required: false
outputs:
  issues:
    description: Issue numbers which may be closed by the pull request, separated by commas.
  opener:
    description: Issue numbers which may be closed by the pull request, that are opened by the pull request opener, separated by commas.
  others:
    description: Issue numbers which may be closed by the pull request, that are opened by other users than the pull request opener, separated by commas.

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository_owner }}
    - ${{ inputs.repository_name }}
    - ${{ inputs.pr_number }}

branding:
  icon: 'box'
  color: 'red'
